### ISSUE TITLE
MacOS arm64 is incompatible

### ISSUE THREAD

**Issue by niazlv** [Proxwian/OxLAUNCHER#18]
Произошла досадная ошибка. Лаунчер macOS не оптимизирован под arm64, от чего запуск лаунчера нативно не удался. Хотел глянуть что за сборки такие, но увы и ах, видимо не судьба

Uncaught Exception:
Error: Cannot open /Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/native/nsfw.node: Error: dlopen(/var/folders/lf/dn2vs4f93ybbv4wrvmtklmqm0000gn/T/.com.proxwian.OxLauncher.Ne62qE, 0x0001): tried: '/var/folders/lf/dn2vs4f93ybbv4wrvmtklmqm0000gn/T/.com.proxwian.OxLauncher.Ne62qE' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/lf/dn2vs4f93ybbv4wrvmtklmqm0000gn/T/.com.proxwian.OxLauncher.Ne62qE' (no such file), '/var/folders/lf/dn2vs4f93ybbv4wrvmtklmqm0000gn/T/.com.proxwian.OxLauncher.Ne62qE' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/private/var/folders/lf/dn2vs4f93ybbv4wrvmtklmqm0000gn/T/.com.proxwian.OxLauncher.Ne62qE' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/lf/dn2vs4f93ybbv4wrvmtklmqm0000gn/T/.com.proxwian.OxLauncher.Ne62qE' (no such file), '/private/var/folders/lf/dn2vs4f93ybbv4wrvmtklmqm0000gn/T/.com.proxwian.OxLauncher.Ne62qE' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
at Object.<anonymous> (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:2734281)
at ./public/native/nsfw.node (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:2734319)
at i (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:124)
at ./public/nsfw.js (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:2734455)
at i (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:124)
at ./public/electron.js (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:2720411)
at i (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:124)
at module.exports../node_modules/base64url/dist/base64url.js (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:923)
at Object.<anonymous> (/Applications/OxLAUNCHER.app/Contents/Resources/app.asar/build/electron.js:2:953)
at Module._compile (node:internal/modules/cjs/loader:1118:14)

**Comment by plsdemo0** [comment]
Согласен, столкнулся с такой же проблемой

**Comment by Artem-Goldenberg** [comment]
Похожая ошибка, но у меня x86 mac
